In [1]:
import pandas as pd

In [11]:
df = pd.read_csv("IPL_Ball_by_Ball_2008_2022.csv")
df

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,2,14,5,P Kumar,I Sharma,SB Joshi,legbyes,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225950,335982,2,14,6,SB Joshi,I Sharma,P Kumar,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225951,335982,2,14,7,P Kumar,I Sharma,SB Joshi,NaN,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225952,335982,2,15,1,SB Joshi,LR Shukla,P Kumar,wides,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225953,335982,2,15,2,SB Joshi,LR Shukla,P Kumar,NaN,0,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore

In [12]:
df.info

<bound method DataFrame.info of              ID  innings  overs  ballnumber       batter          bowler  \
0       1312200        1      0           1  YBK Jaiswal  Mohammed Shami
1       1312200        1      0           2  YBK Jaiswal  Mohammed Shami
2       1312200        1      0           3   JC Buttler  Mohammed Shami
3       1312200        1      0           4  YBK Jaiswal  Mohammed Shami
4       1312200        1      0           5  YBK Jaiswal  Mohammed Shami
...         ...      ...    ...         ...          ...             ...
225949   335982        2     14           5      P Kumar        I Sharma
225950   335982        2     14           6     SB Joshi        I Sharma
225951   335982        2     14           7      P Kumar        I Sharma
225952   335982        2     15           1     SB Joshi       LR Shukla
225953   335982        2     15           2     SB Joshi       LR Shukla

        non-striker extra_type  batsman_run  extras_run  total_run  \
0        JC Buttler        NaN            0           0          0
1        JC Buttler    legbyes            0           1          1
2       YBK Jaiswal        NaN            1           0          1
3        JC Buttler        NaN            0           0          0
4        JC Buttler        NaN            0           0          0
...             ...        ...          ...         ...        ...
225949     SB Joshi    legbyes            0           1          1
225950      P Kumar        NaN            1           0          1
225951     SB Joshi        NaN            0           0          0
225952      P Kumar      wides            0           1          1
225953      P Kumar        NaN            0           0          0

        non_boundary  isWicketDelivery player_out    kind fielders_involved  \
0                  0                 0        NaN     NaN               NaN
1                  0                 0        NaN     NaN               NaN
2                  0                 0        NaN     NaN               NaN
3                  0                 0        NaN     NaN               NaN
4                  0                 0        NaN     NaN               NaN
...              ...               ...        ...     ...               ...
225949             0                 0        NaN     NaN               NaN
225950             0                 0        NaN     NaN               NaN
225951             0                 0        NaN     NaN               NaN
225952             0                 0        NaN     NaN               NaN
225953             0                 1   SB Joshi  caught       BB McCullum

                        BattingTeam
0                  Rajasthan Royals
1                  Rajasthan Royals
2                  Rajasthan Royals
3                  Rajasthan Royals
4                  Rajasthan Royals
...                             ...
225949  Royal Challengers Bangalore
225950  Royal Challengers Bangalore
225951  Royal Challengers Bangalore
225952  Royal Challengers Bangalore
225953  Royal Challengers Bangalore

[225954 rows x 17 columns]>

In [16]:
df.isnull().mean()*100

ID                    0.000000
innings               0.000000
overs                 0.000000
ballnumber            0.000000
batter                0.000000
bowler                0.000000
non-striker           0.000000
extra_type           94.667499
batsman_run           0.000000
extras_run            0.000000
total_run             0.000000
non_boundary          0.000000
isWicketDelivery      0.000000
player_out           95.064925
kind                 95.064925
fielders_involved    96.464767
BattingTeam           0.000000
dtype: float64

In [18]:
df.drop(["extra_type","player_out","kind","fielders_involved"],axis = 1)

,ID,innings,overs,ballnumber,batter,bowler,non-striker,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,0,0,0,0,0,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,0,1,1,0,0,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,1,0,1,0,0,Rajasthan Royals
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,0,0,0,0,0,Rajasthan Royals
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,0,0,0,0,0,Rajasthan Royals
...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,2,14,5,P Kumar,I Sharma,SB Joshi,0,1,1,0,0,Royal Challengers Bangalore
225950,335982,2,14,6,SB Joshi,I Sharma,P Kumar,1,0,1,0,0,Royal Challengers Bangalore
225951,335982,2,14,7,P Kumar,I Sharma,SB Joshi,0,0,0,0,0,Royal Challengers Bangalore
225952,335982,2,15,1,SB Joshi,LR Shukla,P Kumar,0,1,1,0,0,Royal Challengers Bangalore
225953,335982,2,15,2,SB Joshi,LR Shukla,P Kumar,0,0,0,0,1,Royal Challengers Bangalore

In [ ]:
df.head()

In [15]:
df.dtypes

ID                    int64
innings               int64
overs                 int64
ballnumber            int64
batter               object
bowler               object
non-striker          object
extra_type           object
batsman_run           int64
extras_run            int64
total_run             int64
non_boundary          int64
isWicketDelivery      int64
player_out           object
kind                 object
fielders_involved    object
BattingTeam          object
dtype: object

# Data cleaning

In [19]:
df.select_dtypes(include = "int")

,ID,innings,overs,ballnumber,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery
0,1312200,1,0,1,0,0,0,0,0
1,1312200,1,0,2,0,1,1,0,0
2,1312200,1,0,3,1,0,1,0,0
3,1312200,1,0,4,0,0,0,0,0
4,1312200,1,0,5,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
225949,335982,2,14,5,0,1,1,0,0
225950,335982,2,14,6,1,0,1,0,0
225951,335982,2,14,7,0,0,0,0,0
225952,335982,2,15,1,0,1,1,0,0
225953,335982,2,15,2,0,0,0,0,1

In [24]:
df.select_dtypes(include = "object")

,batter,bowler,non-striker,extra_type,player_out,kind,fielders_involved,BattingTeam
0,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,NaN,NaN,NaN,Rajasthan Royals
1,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,NaN,NaN,NaN,Rajasthan Royals
2,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,NaN,NaN,NaN,Rajasthan Royals
3,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,NaN,NaN,NaN,Rajasthan Royals
4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,NaN,NaN,NaN,Rajasthan Royals
...,...,...,...,...,...,...,...,...
225949,P Kumar,I Sharma,SB Joshi,legbyes,NaN,NaN,NaN,Royal Challengers Bangalore
225950,SB Joshi,I Sharma,P Kumar,NaN,NaN,NaN,NaN,Royal Challengers Bangalore
225951,P Kumar,I Sharma,SB Joshi,NaN,NaN,NaN,NaN,Royal Challengers Bangalore
225952,SB Joshi,LR Shukla,P Kumar,wides,NaN,NaN,NaN,Royal Challengers Bangalore
225953,SB Joshi,LR Shukla,P Kumar,NaN,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore

In [27]:
df.select_dtypes(include = ["object","category"]).columns.tolist()

['batter',
 'bowler',
 'non-striker',
 'extra_type',
 'player_out',
 'kind',
 'fielders_involved',
 'BattingTeam']

In [29]:
df['bowler'].unique()

array(['Mohammed Shami', 'Yash Dayal', 'LH Ferguson', 'Rashid Khan',
       'HH Pandya', 'R Sai Kishore', 'TA Boult', 'M Prasidh Krishna',
       'YS Chahal', 'OC McCoy', 'R Ashwin', 'Mohammed Siraj',
       'JR Hazlewood', 'GJ Maxwell', 'Shahbaz Ahmed', 'HV Patel',
       'PWH de Silva', 'Mohsin Khan', 'PVD Chameera', 'KH Pandya',
       'Avesh Khan', 'Ravi Bishnoi', 'AS Joseph', 'LS Livingstone',
       'Arshdeep Singh', 'K Rabada', 'NT Ellis', 'Harpreet Brar',
       'B Kumar', 'Washington Sundar', 'Fazalhaq Farooqi', 'J Suchith',
       'Umran Malik', 'R Shepherd', 'DR Sams', 'HR Shokeen', 'JJ Bumrah',
       'M Markande', 'RP Meredith', 'Ramandeep Singh', 'KK Ahmed',
       'A Nortje', 'SN Thakur', 'MR Marsh', 'Kuldeep Yadav', 'AR Patel',
       'Mukesh Choudhary', 'Simarjeet Singh', 'MJ Santner', 'M Pathirana',
       'MM Ali', 'PH Solanki', 'S Kaul', 'MK Lomror', 'UT Yadav',
       'TG Southee', 'SP Narine', 'CV Varun', 'AD Russell', 'N Rana',
       'JO Holder', 'K Gowtham', 'MP Stoinis', 'R Sanjay Yadav',
       'T Natarajan', 'Abhishek Sharma', 'R Dhawan', 'RD Chahar',
       'Lalit Yadav', 'A Badoni', 'M Jansen', 'K Kartikeya', 'DJ Bravo',
       'M Theekshana', 'C Sakariya', 'KR Sen', 'M Ashwin', 'KA Pollard',
       'PJ Cummins', 'VR Iyer', 'Kartik Tyagi', 'Shivam Mavi', 'AS Roy',
       'Harshit Rana', 'Sandeep Sharma', 'PJ Sangwan', 'R Tewatia',
       'SA Abbott', 'S Gopal', 'AK Markram', 'RA Jadeja', 'D Pretorius',
       'Shashank Singh', 'Mustafizur Rahman', 'DJ Mitchell', 'SS Iyer',
       'JD Unadkat', 'R Parag', 'VG Arora', 'CJ Jordan', 'OF Smith',
       'Tilak Varma', 'TS Mills', 'FA Allen', 'Aman Hakim Khan',
       'JDS Neesham', 'V Shankar', 'Basil Thampi', 'Akash Deep',
       'DG Nalkande', 'Rasikh Salam', 'R Powell', 'DJ Willey', 'D Brevis',
       'AJ Tye', 'Navdeep Saini', 'YBK Jaiswal', 'Abdul Samad',
       'VR Aaron', 'DJ Hooda', 'TU Deshpande', 'S Dube',
       'NM Coulter-Nile', 'KL Nagarkoti', 'AF Milne', 'Shakib Al Hasan',
       'DL Chahar', 'GHS Garton', 'DT Christian', 'TK Curran', 'J Yadav',
       'IC Porel', 'AU Rashid', 'CH Morris', 'KA Jamieson', 'GD Phillips',
       'RV Patel', 'SM Curran', 'T Shamsi', 'RG Sharma', 'MC Henriques',
       'K Yadav', 'S Sandeep Warrier', 'Akash Singh', 'KM Asif',
       'Mohammad Nabi', 'PP Chawla', 'I Sharma', 'DS Kulkarni', 'L Ngidi',
       'A Mishra', 'Imran Tahir', 'KW Richardson', 'CR Woakes',
       'LI Meriwala', 'Jalaj S Saxena', 'JA Richardson',
       'Harbhajan Singh', 'Mujeeb Ur Rahman', 'S Nadeem', 'BA Stokes',
       'P Dubey', 'A Zampa', 'JL Pattinson', 'I Udana', 'Monu Kumar',
       'JC Archer', 'SS Cottrell', 'AS Rajpoot', 'KS Williamson',
       'KV Sharma', 'DW Steyn', 'CJ Green', 'DA Warner', 'CH Gayle',
       'MM Sharma', 'MJ McClenaghan', 'SL Malinga', 'KMA Paul',
       'SE Rutherford', 'HF Gurney', 'K Khejroliya', 'C de Grandhomme',
       'O Thomas', 'IS Sodhi', 'STR Binny', 'BB Sran', 'S Lamichhane',
       'CR Brathwaite', 'Y Prithvi Raj', 'GC Viljoen', 'P Negi',
       'KC Cariappa', 'Mandeep Singh', 'JP Behrendorff', 'SN Khan',
       'SC Kuggeleijn', 'S Midhun', 'YK Pathan', 'GH Vihari',
       'P Ray Barman', 'BCJ Cutting', 'SK Raina', 'B Laughlin',
       'JPR Scantlebury-Searles', 'LE Plunkett', 'Anureet Singh',
       'SR Watson', 'CJ Dala', 'Ankit Sharma', 'MG Johnson', 'JP Duminy',
       'MK Tiwary', 'CJ Anderson', 'B Stanlake', 'Yuvraj Singh',
       'DJM Short', 'A Dananjaya', 'R Vinay Kumar', 'MA Wood',
       'Bipul Sharma', 'Z Khan', 'TM Head', 'Swapnil Singh', 'P Kumar',
       'JP Faulkner', 'MM Patel', 'Ankit Soni', 'MN Samuels', 'MJ Henry',
       'DR Smith', 'A Choudhary', 'S Badree', 'S Aravind', 'A Nehra',
       'IK Pathan', 'NB Singh', 'RA Tripathi', 'SS Agarwal', 'AD Mathews',
       'S Kaushik', 'SB Jakati', 'AB Dinda', 'R Bhatia', 'Iqbal Abdulla',
       'Tejas Baroka', 'MS Gony', 'M Morkel', 'R Sathish', 'C Munro',
       'NLTC Perera', 'KJ Abbott', 'Gurkeerat Singh', 'Sachin Baby',
       'M Vijay', 'PV Tambe', 'V Kohli', 'RP Singh', 'GB Hogg',
       'Parvez Rasool', 'SM Boland', 'JA Morkel', 'P Sahu', 'D Wiese',
       'A Ashish Reddy', 'JW Hastings', 'S Ladda', 'MA Starc',
       'Azhar Mahmood', 'IC Pandey', 'BE Hendricks', 'GS Sandhu',
       'RS Bopara', 'J Botha', 'M de Lange', 'Karanveer Singh',
       'RN ten Doeschate', 'RG More', 'J Theron', 'DJ Muthuswami',
       'Shivam Sharma', 'AN Ahmed', 'P Suyal', 'DJG Sammy', 'PP Ojha',
       'L Balaji', 'P Awana', 'KK Cooper', 'R Rampaul', 'S Rana',
       'VS Malik', 'WD Parnell', 'M Muralitharan', 'K Santokie',
       'BW Hilfenhaus', 'Y Venugopal Rao', 'DJ Hussey', 'R Shukla',
       'LMP Simmons', 'JH Kallis', 'LR Shukla', 'M Kartik', 'SA Yadav',
       'R Sharma', 'SK Trivedi', 'Anand Rajan', 'AG Murtaza',
       'AC Gilchrist', 'BJ Hodge', 'MG Neser', 'AA Chavan',
       'RE van der Merwe', 'SMSM Senanayake', 'LJ Wright', 'RV Gomez',
       'Harmeet Singh', 'BA Bhatt', 'AB Agarkar', 'A Mithun',
       'BAW Mendis', 'J Syed Mohammad', 'K Upadhyay', 'A Chandila',
       'S Sreesanth', 'R McLaren', 'SW Tait', 'BJ Rohrer', 'CL White',
       'BMAJ Mendis', 'S Narwal', 'TL Suman', 'B Lee', 'AM Nayar',
       'DP Nannes', 'AJ Finch', 'AD Mascarenhas', 'V Sehwag',
       'AB McDonald', 'RJ Harris', 'TM Dilshan', 'JDP Oram',
       'Sunny Gupta', 'JEC Franklin', 'P Parameswaran', 'V Pratap Singh',
       'MJ Clarke', 'SC Ganguly', 'VY Mahesh', 'KP Appanna',
       'TP Sudhindra', 'AA Jhunjhunwala', 'JD Ryder', 'AC Thomas',
       'Pankaj Singh', 'S Dhawan', 'DJ Harris', 'RR Powar', 'SPD Smith',
       'RJ Peterson', 'DL Vettori', 'AUK Pathan', 'A Singh', 'AL Menaria',
       'KMDN Kulasekara', 'CJ McKay', 'KP Pietersen', 'Y Nagar',
       'DE Bollinger', 'RR Bhatkal', 'F du Plessis', 'DAJ Bracewell',
       'PC Valthaty', 'RW Price', 'SS Mundhe', 'SK Warne',
       'JJ van der Wath', 'CK Langeveldt', 'SJ Srivastava', 'M Manhas',
       'P Prasanth', 'Y Gnaneswara Rao', 'ND Doshi', 'AM Salvi',
       'JR Hopes', 'S Sriram', 'AA Kazi', 'LRPL Taylor', 'SB Wagh',
       'A Symonds', 'S Randiv', 'L Ablish', 'I Malhotra', 'B Chipli',
       'JE Taylor', 'NL McCullum', 'B Akhil', 'Kamran Khan',
       'Joginder Sharma', 'AS Raut', 'R Ninan', 'SB Styris',
       'DB Ravi Teja', 'NJ Rimmington', 'CRD Fernando', 'A Kumble',
       'SE Bond', 'PD Collingwood', 'WPUJC Vaas', 'S Tyagi', 'JM Kemp',
       'VRV Singh', 'AC Voges', 'FY Fazal', 'AP Dole', 'ST Jayasuriya',
       'MF Maharoof', 'T Thushara', 'Jaskaran Singh', 'KAJ Roach',
       'MB Parmar', 'C Ganapathy', 'K Goel', 'YA Abdulla', 'A Uniyal',
       'RS Gavaskar', 'RA Shaikh', 'WA Mota', 'SS Sarkar', 'T Henderson',
       'Mashrafe Mortaza', 'C Nanda', 'Shoaib Ahmed', 'RR Raje',
       'AM Rahane', 'SM Harwood', 'SR Tendulkar', 'LA Carseldine',
       'D du Preez', 'FH Edwards', 'GR Napier', 'RR Bose', 'A Flintoff',
       'Sohail Tanvir', 'M Ntini', 'GD McGrath', 'Mohammad Asif',
       'DP Vijaykumar', 'Shahid Afridi', 'PM Sarvesh Kumar', 'SM Pollock',
       'Umar Gul', 'SB Bangar', 'D Salunkhe', 'B Geeves', 'A Nel',
       'Gagandeep Singh', 'VS Yeligati', 'SD Chitnis', 'Shoaib Akhtar',
       'DNT Zoysa', 'DJ Thornely', 'Abdur Razzak', 'CK Kapugedera',
       'P Amarnath', 'Shoaib Malik', 'S Vidyut', 'Mohammad Hafeez',
       'LPC Silva', 'D Kalyankrishna', 'SB Joshi', 'MA Khote',
       'AA Noffke'], dtype=object)