In [25]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

In [26]:
df = pd.read_csv("World_Stock_prices_Dataset.csv")
df

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Capital Gains
0,2025-03-20 00:00:00-04:00,386.899994,397.820007,385.799988,389.609985,4003800,0.0,0.0,adobe,ADBE,technology,usa,NaN
1,2025-03-20 00:00:00-04:00,131.100006,132.289993,130.210007,130.509995,378500,0.0,0.0,lvmh,LVMUY,luxury goods,france,NaN
2,2025-03-20 00:00:00-04:00,236.559998,241.759995,236.199997,239.009995,8321600,0.0,0.0,jpmorgan chase & co,JPM,finance,usa,NaN
3,2025-03-20 00:00:00-04:00,60.480000,61.020000,60.340000,60.619999,16503100,0.0,0.0,cisco,CSCO,technology,usa,NaN
4,2025-03-20 00:00:00-04:00,59.020000,59.290001,58.689999,59.230000,2840400,0.0,0.0,unilever,UL,consumer goods,netherlands,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
305209,2000-01-03 00:00:00-05:00,13.822670,13.822670,13.675379,13.720699,48000,0.0,0.0,honda,HMC,automotive,japan,NaN
305210,2000-01-03 00:00:00-05:00,3.990652,4.061914,3.848129,3.990652,134500,0.0,0.0,nintendo,NTDOY,gaming,japan,NaN
305211,2000-01-03 00:00:00-05:00,31.512873,31.512873,30.431443,30.799129,6057400,0.0,0.0,costco,COST,retail,usa,NaN
305212,2000-01-03 00:00:00-05:00,38.147537,38.255972,35.935457,37.496925,53076000,0.0,0.0,cisco,CSCO,technology,usa,NaN
305213,2000-01-03 00:00:00-05:00,5.731675,5.793975,5.427959,5.482471,5825700,0.0,0.0,american eagle outfitters,AEO,apparel,usa,NaN

In [27]:
# ef = pd.read_excel("World_Stock_prices_Dataset.xlsx")
# ef

In [28]:
df.ndim

2

In [29]:
df.shape

(305214, 13)

In [30]:
df.size

3967782

In [31]:
df.dtypes

Date              object
Open             float64
High             float64
Low              float64
Close            float64
Volume             int64
Dividends        float64
Stock Splits     float64
Brand_Name        object
Ticker            object
Industry_Tag      object
Country           object
Capital Gains    float64
dtype: object

In [32]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Dividends',
       'Stock Splits', 'Brand_Name', 'Ticker', 'Industry_Tag', 'Country',
       'Capital Gains'],
      dtype='object')

In [33]:
df.info

<bound method DataFrame.info of                              Date        Open        High         Low  \
0       2025-03-20 00:00:00-04:00  386.899994  397.820007  385.799988
1       2025-03-20 00:00:00-04:00  131.100006  132.289993  130.210007
2       2025-03-20 00:00:00-04:00  236.559998  241.759995  236.199997
3       2025-03-20 00:00:00-04:00   60.480000   61.020000   60.340000
4       2025-03-20 00:00:00-04:00   59.020000   59.290001   58.689999
...                           ...         ...         ...         ...
305209  2000-01-03 00:00:00-05:00   13.822670   13.822670   13.675379
305210  2000-01-03 00:00:00-05:00    3.990652    4.061914    3.848129
305211  2000-01-03 00:00:00-05:00   31.512873   31.512873   30.431443
305212  2000-01-03 00:00:00-05:00   38.147537   38.255972   35.935457
305213  2000-01-03 00:00:00-05:00    5.731675    5.793975    5.427959

             Close    Volume  Dividends  Stock Splits  \
0       389.609985   4003800        0.0           0.0
1       130.509995    378500        0.0           0.0
2       239.009995   8321600        0.0           0.0
3        60.619999  16503100        0.0           0.0
4        59.230000   2840400        0.0           0.0
...            ...       ...        ...           ...
305209   13.720699     48000        0.0           0.0
305210    3.990652    134500        0.0           0.0
305211   30.799129   6057400        0.0           0.0
305212   37.496925  53076000        0.0           0.0
305213    5.482471   5825700        0.0           0.0

                       Brand_Name Ticker    Industry_Tag      Country  \
0                           adobe   ADBE      technology          usa
1                            lvmh  LVMUY    luxury goods       france
2             jpmorgan chase & co    JPM         finance          usa
3                           cisco   CSCO      technology          usa
4                        unilever     UL  consumer goods  netherlands
...                           ...    ...             ...          ...
305209                      honda    HMC      automotive        japan
305210                   nintendo  NTDOY          gaming        japan
305211                     costco   COST          retail          usa
305212                      cisco   CSCO      technology          usa
305213  american eagle outfitters    AEO         apparel          usa

        Capital Gains
0                 NaN
1                 NaN
2                 NaN
3                 NaN
4                 NaN
...               ...
305209            NaN
305210            NaN
305211            NaN
305212            NaN
305213            NaN

[305214 rows x 13 columns]>

In [34]:
df.describe()

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains
count,305214.000000,305214.000000,305214.000000,305214.000000,3.052140e+05,305214.000000,305214.000000,2.0
mean,74.641161,75.486977,73.772223,74.647712,2.282449e+07,0.003619,0.000889,0.0
std,139.608377,141.104907,138.013404,139.585562,8.620156e+07,0.069804,0.116359,0.0
min,0.196890,0.199922,0.192798,0.198861,0.000000e+00,0.000000,0.000000,0.0
25%,15.788243,16.004417,15.568016,15.790000,1.370100e+06,0.000000,0.000000,0.0
50%,34.909502,35.321240,34.485629,34.921560,4.581700e+06,0.000000,0.000000,0.0
75%,81.632358,82.479252,80.797011,81.617733,1.212660e+07,0.000000,0.000000,0.0
max,3445.580078,3463.070068,3370.000000,3427.610107,7.421641e+09,15.000000,50.000000,0.0